-- 프로그래머스 SQL 고득점 KIT (JOIN)
-- https://school.programmers.co.kr/learn/courses/30/lessons/131117

SELECT FO.PRODUCT_ID,
       FP.PRODUCT_NAME,
       SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS FO
    INNER JOIN FOOD_PRODUCT AS FP ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE YEAR(FO.PRODUCE_DATE) = 2022 AND MONTH(FO.PRODUCE_DATE) = 5
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;