-- 프로그래머스 SQL 고득점 KIT (JOIN)
-- https://school.programmers.co.kr/learn/courses/30/lessons/59042

SELECT AO.ANIMAL_ID,
       AO.NAME
FROM ANIMAL_OUTS AS AO
    LEFT JOIN ANIMAL_INS AS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID;