-- 실패..!
-- 프로그래머스 SQL 고득점 KIT (JOIN)
-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

SELECT C.CAR_ID,
       C.CAR_TYPE,
       ROUND(DAILY_FEE * 30 * (1 - (DISCOUNT_RATE / 100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
      AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
        OR END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
        OR (START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30')
      )
AND DURATION_TYPE = '30일 이상'
AND ROUND(DAILY_FEE * 30 * (1 - (DISCOUNT_RATE / 100))) BETWEEN 500000 AND 2000000
GROUP BY C.CAR_ID
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;